name: gym_force
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  camera: ^0.11.0+2
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.3
  flutter:
    sdk: flutter
  flutter_face_api: ^6.3.591
  flutter_riverpod: ^2.5.1
  go_router: ^14.3.0
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  url_launcher: ^6.3.0
  geolocator: ^10.0.0
  pretty_qr_code: ^3.3.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/memberships_wallpaper.png
