// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwwu7haCVNeH6iJw66bjnN_pzj9ZIG7BA',
    appId: '1:840636761514:web:5efb4ac40569c2a806d7d3',
    messagingSenderId: '840636761514',
    projectId: 'gymforce-cde2c',
    authDomain: 'gymforce-cde2c.firebaseapp.com',
    storageBucket: 'gymforce-cde2c.appspot.com',
    measurementId: 'G-FT339TGN64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmDIxOi3CLDazSmmxvJ2gVRGOg62pu93E',
    appId: '1:840636761514:android:f0ec09aa0dd09fb006d7d3',
    messagingSenderId: '840636761514',
    projectId: 'gymforce-cde2c',
    storageBucket: 'gymforce-cde2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOjB0B_52FJkIQBi_jAjAGdnbjmJWe59M',
    appId: '1:840636761514:ios:9ed14836376df35106d7d3',
    messagingSenderId: '840636761514',
    projectId: 'gymforce-cde2c',
    storageBucket: 'gymforce-cde2c.appspot.com',
    iosBundleId: 'com.example.gymForce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOjB0B_52FJkIQBi_jAjAGdnbjmJWe59M',
    appId: '1:840636761514:ios:9ed14836376df35106d7d3',
    messagingSenderId: '840636761514',
    projectId: 'gymforce-cde2c',
    storageBucket: 'gymforce-cde2c.appspot.com',
    iosBundleId: 'com.example.gymForce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwwu7haCVNeH6iJw66bjnN_pzj9ZIG7BA',
    appId: '1:840636761514:web:d5b423eca08fbf7206d7d3',
    messagingSenderId: '840636761514',
    projectId: 'gymforce-cde2c',
    authDomain: 'gymforce-cde2c.firebaseapp.com',
    storageBucket: 'gymforce-cde2c.appspot.com',
    measurementId: 'G-YG2QYP0SHF',
  );
}
